"""Streamlit app for experimenting with video-based long exposure images."""

from __future__ import annotations

import base64
from dataclasses import dataclass, replace
from html import escape
from pathlib import Path
import shutil
import tempfile
import time
from typing import cast
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse
from urllib.request import Request, urlopen
import uuid

import cv2
import numpy as np
import pandas as pd
import streamlit as st
from PIL import Image

try:
    from streamlit_drawable_canvas import st_canvas
except ImportError:  # pragma: no cover - depends on local environment install
    st_canvas = None

from longexposure.blending import (
    extract_paint_mask_from_canvas,
    make_alignment_allowed_mask,
)
from longexposure.diagnostics import (
    accepted_rejected_figure,
    inlier_ratio_figure,
    sharpness_figure,
)
from longexposure.frames import ReferenceStrategy
from longexposure.io import get_video_summary, save_uploaded_video_to_temp
from longexposure.pipeline import (
    PipelineResult,
    PipelineSettings,
    PreviewResult,
    run_preview,
    run_pipeline,
    stack_alignment_subset,
    stackable_alignment_order,
)
from longexposure.stacking import StackingMode


APP_TITLE = "Video Long Exposure Lab"
OUTPUT_DIR = Path("outputs")
SAMPLE_DATA_DIR = Path("sample_data")
PREVIEW_RESIZE_WIDTH = 800
PREVIEW_FRAME_REFRESH_THRESHOLD = 120
MAX_UPLOAD_VIDEO_BYTES = 25 * 1024 * 1024
MAX_REMOTE_VIDEO_BYTES = 250 * 1024 * 1024
STALE_TEMP_SECONDS = 6 * 60 * 60
APP_TEMP_ROOT = Path(tempfile.gettempdir()) / "video-long-exposure-lab"
LOCAL_SAMPLE_SUFFIXES = {".m4v", ".mov", ".mp4"}
VIDEO_MIME_TYPES = {
    ".m4v": "video/mp4",
    ".mov": "video/quicktime",
    ".mp4": "video/mp4",
}
STACKING_MODE_LABELS: dict[str, StackingMode] = {
    "Mean photographic average": "mean",
    "Median": "median",
    "Sigma-clipped mean": "sigma_clipped_mean",
    "Lighten / star trails": "lighten",
    "Additive / sum": "additive",
}
STACKING_MODE_GUIDANCE = {
    "mean": "Best for waterfalls, streams, clouds, and smoothing motion.",
    "median": "Useful for cleanup, but it suppresses transient motion.",
    "sigma_clipped_mean": "Cleanup-oriented mean; can be slower at full resolution.",
    "lighten": "Best for star trails, light trails, and fireworks.",
    "additive": "Experimental; brightens quickly and can saturate highlights.",
}
OUTPUT_SECTION_LABELS = {
    "additive": "Additive Stack",
    "lighten": "Lighten / Star Trails Stack",
    "mean": "Photographic Full-Frame Average",
    "median": "Median Stack",
    "sigma_clipped_mean": "Sigma-Clipped Mean Stack",
}
BEST_RESULTS_TIPS = [
    "Use full-resolution video.",
    "Keep the camera as still as possible.",
    "Include static rocks, trees, buildings, or landscape for alignment.",
    "Avoid extreme parallax between foreground and background.",
    "Avoid heavy wind in foliage when it is needed for alignment.",
    "Use 2-5 seconds for waterfalls and streams.",
]
DEMO_RELEASE_URL = (
    "https://github.com/michaelm-503/video-long-exposure-lab/"
    "releases/tag/demo-media-v1"
)
DEMO_RELEASE_ASSETS_BASE = (
    "https://github.com/michaelm-503/video-long-exposure-lab/"
    "releases/download/demo-media-v1"
)
DEMO_SOURCES = [
    {
        "title": "Ashford A30 Traffic",
        "kind": "Traffic",
        "filename": "roadway_1.mp4",
        "description": "Road traffic sample for light-trail and additive stacking demos.",
        "source_url": "https://www.flickr.com/photos/mualphachi/3809913910",
        "url": f"{DEMO_RELEASE_ASSETS_BASE}/roadway_1.mp4",
        "author": "Maxwell Hamilton",
        "author_url": "https://www.flickr.com/photos/mualphachi/",
        "license": "CC BY 2.0",
        "license_url": "https://creativecommons.org/licenses/by/2.0/deed.en",
        "changes": "Rehosted for demo use; processed outputs generated by Video Long Exposure Lab.",
    },
    {
        "title": "Zakim Bridge Traffic Wide (HD)",
        "kind": "Traffic",
        "filename": "roadway_2.mp4",
        "description": "Wide bridge traffic sample for light trails and frame averaging.",
        "source_url": "https://www.flickr.com/photos/ekilby/3954977794",
        "url": f"{DEMO_RELEASE_ASSETS_BASE}/roadway_2.mp4",
        "author": "Eric Kilby",
        "author_url": "https://www.flickr.com/photos/ekilby/",
        "license": "CC BY-SA 2.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/2.0/deed.en",
        "changes": "Rehosted for demo use; processed outputs generated by Video Long Exposure Lab.",
    },
    {
        "title": "Sunset",
        "kind": "Sky",
        "filename": "sunset.mov",
        "description": "Sunset clip for clouds, sky movement, and soft-light averaging.",
        "source_url": "",
        "url": f"{DEMO_RELEASE_ASSETS_BASE}/sunset.mov",
        "author": "Michael Moore",
        "author_url": "",
        "license": "CC BY 2.0",
        "license_url": "https://creativecommons.org/licenses/by/2.0/deed.en",
        "changes": "",
    },
    {
        "title": "Waterfall 1",
        "kind": "Waterfall",
        "filename": "waterfall_1.MOV",
        "description": "Waterfall clip for photographic mean averaging.",
        "source_url": "",
        "url": f"{DEMO_RELEASE_ASSETS_BASE}/waterfall_1.MOV",
        "author": "Michael Moore",
        "author_url": "",
        "license": "CC BY 2.0",
        "license_url": "https://creativecommons.org/licenses/by/2.0/deed.en",
        "changes": "",
    },
    {
        "title": "Waterfall 2",
        "kind": "Waterfall",
        "filename": "waterfall_2.MOV",
        "description": "Waterfall clip for stream smoothing and alignment tests.",
        "source_url": "",
        "url": f"{DEMO_RELEASE_ASSETS_BASE}/waterfall_2.MOV",
        "author": "Michael Moore",
        "author_url": "",
        "license": "CC BY 2.0",
        "license_url": "https://creativecommons.org/licenses/by/2.0/deed.en",
        "changes": "",
    },
    {
        "title": "Waterfall 3",
        "kind": "Waterfall",
        "filename": "waterfall_3.MOV",
        "description": "Waterfall clip with more motion and border-crop pressure.",
        "source_url": "",
        "url": f"{DEMO_RELEASE_ASSETS_BASE}/waterfall_3.MOV",
        "author": "Michael Moore",
        "author_url": "",
        "license": "CC BY 2.0",
        "license_url": "https://creativecommons.org/licenses/by/2.0/deed.en",
        "changes": "",
    },
    {
        "title": "Devil's Cataract video",
        "kind": "Waterfall",
        "filename": "waterfall_4.mp4",
        "description": "Waterfall source for long-exposure-style smoothing demos.",
        "source_url": "https://www.flickr.com/photos/dalangalma/8199506986",
        "url": f"{DEMO_RELEASE_ASSETS_BASE}/waterfall_4.mp4",
        "author": "Benjamin Hollis",
        "author_url": "https://www.flickr.com/photos/dalangalma/",
        "license": "CC BY 2.0",
        "license_url": "https://creativecommons.org/licenses/by/2.0/deed.en",
        "changes": "Rehosted for demo use; processed outputs generated by Video Long Exposure Lab.",
    },
]


@dataclass(frozen=True)
class VideoSelection:
    """Resolved video input for one app run."""

    name: str
    suffix: str
    video_bytes: bytes | None
    video_path: Path
    signature: tuple[object, ...]
    cleanup_path: bool


def _session_temp_id() -> str:
    """Return a stable per-session ID for temp file isolation."""
    if "temp_session_id" not in st.session_state:
        st.session_state.temp_session_id = uuid.uuid4().hex
    return cast(str, st.session_state.temp_session_id)


def _session_temp_dir() -> Path:
    """Return this user's temp directory for video files."""
    session_id = _session_temp_id()
    _prune_stale_session_temp_dirs(session_id)
    temp_dir = APP_TEMP_ROOT / session_id
    temp_dir.mkdir(parents=True, exist_ok=True)
    return temp_dir


def _prune_stale_session_temp_dirs(current_session_id: str) -> None:
    """Remove abandoned session temp directories from previous Cloud sessions."""
    if not APP_TEMP_ROOT.exists():
        return

    now = time.time()
    for path in APP_TEMP_ROOT.iterdir():
        if path.name == current_session_id or not path.is_dir():
            continue
        try:
            if now - path.stat().st_mtime > STALE_TEMP_SECONDS:
                shutil.rmtree(path, ignore_errors=True)
        except OSError:
            continue


def _clear_processing_state() -> None:
    """Clear cached results tied to the active video."""
    for key in (
        "demo_video_selection",
        "video_signature",
        "preview_result",
        "preview_signature",
        "guided_result",
        "guided_settings",
        "canvas_nonce",
        "active_upload_signature",
    ):
        st.session_state.pop(key, None)
    _cached_video_summary.clear()


def _cleanup_session_temp_files() -> None:
    """Remove temp files for this session before loading a new video."""
    temp_dir = _session_temp_dir()
    shutil.rmtree(temp_dir, ignore_errors=True)
    temp_dir.mkdir(parents=True, exist_ok=True)
    _clear_processing_state()


def _write_session_temp_video(video_bytes: bytes, suffix: str) -> Path:
    """Write video bytes into the current session's temp directory."""
    temp_file = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=suffix,
        dir=_session_temp_dir(),
    )
    try:
        temp_file.write(video_bytes)
    finally:
        temp_file.close()
    return Path(temp_file.name)


def _video_bytes_for_display(selection: VideoSelection) -> bytes:
    """Return video bytes for the HTML preview without storing demos in session."""
    if selection.video_bytes is not None:
        return selection.video_bytes
    try:
        return selection.video_path.read_bytes()
    except OSError as error:
        raise ValueError("The temporary video file is no longer available. Load the video again.") from error


def _inject_ui_styles() -> None:
    """Keep media previews content-sized in Streamlit 1.40."""
    st.markdown(
        """
        <style>
            video.content-sized-video {
                display: block;
                max-width: 100%;
                max-height: 70vh;
                height: auto;
            }
        </style>
        """,
        unsafe_allow_html=True,
    )


def _encode_image(image_bgr: np.ndarray, extension: str) -> bytes:
    """Encode a BGR image for downloads."""
    encode_params = [cv2.IMWRITE_JPEG_QUALITY, 95] if extension == ".jpg" else []
    ok, encoded = cv2.imencode(extension, image_bgr, encode_params)
    if not ok:
        raise ValueError(f"Could not encode image as {extension}")
    return encoded.tobytes()


def _encode_gray_png(mask: np.ndarray) -> bytes:
    """Encode a 2D mask as PNG bytes."""
    ok, encoded = cv2.imencode(".png", np.clip(mask, 0, 255).astype(np.uint8))
    if not ok:
        raise ValueError("Could not encode alpha mask as PNG")
    return encoded.tobytes()


def _save_output_images(image_bgr: np.ndarray) -> tuple[Path, Path]:
    """Save PNG and JPEG outputs locally for portfolio/demo runs."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    png_path = OUTPUT_DIR / "long_exposure.png"
    jpg_path = OUTPUT_DIR / "long_exposure.jpg"
    cv2.imwrite(str(png_path), image_bgr)
    cv2.imwrite(str(jpg_path), image_bgr, [cv2.IMWRITE_JPEG_QUALITY, 95])
    return png_path, jpg_path


def _render_video(
    video_bytes: bytes,
    *,
    suffix: str,
    video_width: int,
) -> None:
    """Render video at its intrinsic width or shrink to fit."""
    encoded_video = base64.b64encode(video_bytes).decode("ascii")
    mime_type = VIDEO_MIME_TYPES.get(suffix.lower(), "video/mp4")
    max_width = min(PREVIEW_RESIZE_WIDTH, max(1, video_width))
    st.markdown(
        f"""
        <video class="content-sized-video" controls preload="metadata"
            style="width: min({max_width}px, 100%);">
            <source src="data:{mime_type};base64,{encoded_video}" type="{mime_type}">
        </video>
        """,
        unsafe_allow_html=True,
    )


def _sample_video_files() -> list[Path]:
    """Return local demo videos that are intentionally untracked by git."""
    if not SAMPLE_DATA_DIR.exists():
        return []

    return sorted(
        path
        for path in SAMPLE_DATA_DIR.iterdir()
        if path.is_file() and path.suffix.lower() in LOCAL_SAMPLE_SUFFIXES
    )


def _load_local_video(path: Path) -> VideoSelection:
    """Build a video selection from a local sample file."""
    stat = path.stat()
    return VideoSelection(
        name=path.name,
        suffix=path.suffix,
        video_bytes=None,
        video_path=path,
        signature=("local", str(path.resolve()), stat.st_size, stat.st_mtime_ns),
        cleanup_path=False,
    )


def _download_video_url(url: str) -> VideoSelection:
    """Download a direct remote video URL to a temporary file."""
    parsed = urlparse(url.strip())
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError("Enter a valid http or https video URL.")

    suffix = Path(parsed.path).suffix.lower()
    request = Request(
        url,
        headers={"User-Agent": "video-long-exposure-lab/1.0"},
    )
    try:
        with urlopen(request, timeout=45) as response:
            content_type = response.headers.get("Content-Type", "").lower()
            content_length = response.headers.get("Content-Length")
            content_length_bytes = (
                int(content_length) if content_length and content_length.isdigit() else 0
            )
            if content_length_bytes > MAX_REMOTE_VIDEO_BYTES:
                raise ValueError("Remote video is larger than the demo download limit.")
            if not content_type.startswith("video/") and suffix not in LOCAL_SAMPLE_SUFFIXES:
                raise ValueError(
                    "That link did not look like a direct video file. Open the source page, "
                    "copy a direct .mp4/.mov/.m4v video URL, or place the clip in sample_data/."
                )

            chunks: list[bytes] = []
            bytes_read = 0
            while True:
                chunk = response.read(1024 * 1024)
                if not chunk:
                    break
                bytes_read += len(chunk)
                if bytes_read > MAX_REMOTE_VIDEO_BYTES:
                    raise ValueError("Remote video is larger than the demo download limit.")
                chunks.append(chunk)
    except HTTPError as error:
        raise ValueError(f"Could not download the video URL: HTTP {error.code}.") from error
    except URLError as error:
        raise ValueError(f"Could not download the video URL: {error.reason}.") from error
    except TimeoutError as error:
        raise ValueError("Could not download the video URL before the connection timed out.") from error
    except OSError as error:
        raise ValueError(f"Could not download the video URL: {error}.") from error

    video_bytes = b"".join(chunks)
    if not video_bytes:
        raise ValueError("No video bytes could be downloaded from that URL.")

    if suffix not in LOCAL_SAMPLE_SUFFIXES:
        if "quicktime" in content_type:
            suffix = ".mov"
        elif "mp4" in content_type:
            suffix = ".mp4"
        else:
            suffix = ".mp4"

    video_path = _write_session_temp_video(video_bytes, suffix)

    return VideoSelection(
        name=Path(parsed.path).name or "remote-demo-video",
        suffix=suffix,
        video_bytes=None,
        video_path=video_path,
        signature=("remote", url, len(video_bytes)),
        cleanup_path=False,
    )


def _demo_title_html(source: dict[str, str]) -> str:
    """Return linked title markup for a demo source."""
    title = source.get("title") or source["filename"]
    source_url = source.get("source_url", "")
    if source_url:
        return (
            f'<a href="{escape(source_url)}" target="_blank" '
            f'rel="noopener noreferrer">{escape(title)}</a>'
        )
    return escape(title)


def _demo_author_html(source: dict[str, str]) -> str:
    """Return linked author markup for a demo source."""
    author = source["author"]
    author_url = source.get("author_url", "")
    if author_url:
        return (
            f'<a href="{escape(author_url)}" target="_blank" '
            f'rel="noopener noreferrer">{escape(author)}</a>'
        )
    return escape(author)


def _demo_license_html(source: dict[str, str]) -> str:
    """Return linked license markup for a demo source."""
    return (
        f'<a href="{escape(source["license_url"])}" target="_blank" '
        f'rel="license noopener noreferrer">{escape(source["license"])}</a>'
    )


def _demo_changes_html(source: dict[str, str]) -> str:
    """Return optional changes markup for a rehosted demo source."""
    changes = source.get("changes", "")
    if not changes:
        return ""

    return (
        '<div style="font-size: 0.8rem; color: #6b7280; margin-top: 0.35rem;">'
        f"{escape(changes)}"
        "</div>"
    )


def _render_demo_source_cards() -> VideoSelection | None:
    """Render compact source cards for the demo gallery."""
    columns = st.columns(3)
    for index, source in enumerate(DEMO_SOURCES):
        with columns[index % len(columns)]:
            st.markdown(
                f"""
                <div style="
                    border: 1px solid #e6e8ef;
                    border-radius: 6px;
                    padding: 0.75rem;
                    margin-bottom: 0.75rem;
                ">
                    <div style="font-weight: 650;">{_demo_title_html(source)}</div>
                    <div style="font-size: 0.9rem; margin-top: 0.55rem;">{escape(source['description'])}</div>
                    <div style="font-size: 0.85rem; margin-top: 0.5rem;">
                        {_demo_author_html(source)} ({_demo_license_html(source)})
                    </div>
                    {_demo_changes_html(source)}
                </div>
                """,
                unsafe_allow_html=True,
            )
            if st.button(
                "Use this demo",
                key=f"use_demo_{source['filename']}",
                use_container_width=True,
            ):
                _cleanup_session_temp_files()
                return _download_video_url(source["url"])
    return None


def _render_demo_gallery() -> VideoSelection | None:
    """Render demo source options and return a selected local/remote video."""
    st.subheader("Demo Gallery")
    st.write(
        "Choose a hosted demo clip, use a local sample file, or paste a direct video URL. "
        "Demo clips are stored as GitHub Release assets so the repo stays small."
    )
    card_selection = _render_demo_source_cards()
    if card_selection is not None:
        return card_selection
    st.markdown(f"[Open demo media release]({DEMO_RELEASE_URL})")

    gallery_columns = st.columns(2)
    local_files = _sample_video_files()
    with gallery_columns[0]:
        st.markdown("**Local sample video**")
        if local_files:
            selected_local = st.selectbox(
                "sample_data videos",
                options=local_files,
                format_func=lambda path: path.name,
            )
            if st.button("Use local sample", type="primary"):
                _cleanup_session_temp_files()
                return _load_local_video(selected_local)
        else:
            st.info("Place .mp4, .mov, or .m4v files in sample_data/ to use them here.")

    with gallery_columns[1]:
        st.markdown("**Direct video URL**")
        direct_url = st.text_input(
            "Direct .mp4/.mov/.m4v URL",
            value="",
            placeholder="https://example.com/sample.mp4",
        )
        if st.button("Load video URL", type="primary"):
            _cleanup_session_temp_files()
            return _download_video_url(direct_url)

    return st.session_state.get("demo_video_selection")


def _render_video_input() -> VideoSelection | None:
    """Render upload/demo input choices and return the active video."""
    input_mode = st.radio(
        "Select video source",
        ["Upload video", "Demo gallery"],
        horizontal=True,
    )

    if input_mode == "Demo gallery":
        selection = _render_demo_gallery()
        if isinstance(selection, VideoSelection):
            st.session_state.demo_video_selection = selection
        return st.session_state.get("demo_video_selection")

    uploaded_file = st.file_uploader(
        "Upload a short video",
        type=["mov", "mp4", "m4v"],
        accept_multiple_files=False,
        help="Use clips up to 25 MB. For Streamlit Cloud, 2K or smaller video is strongly recommended.",
    )
    if uploaded_file is None:
        return None

    uploaded_bytes = uploaded_file.getvalue()
    if len(uploaded_bytes) > MAX_UPLOAD_VIDEO_BYTES:
        raise ValueError("Upload a video that is 25 MB or smaller for the Streamlit demo.")

    suffix = Path(uploaded_file.name).suffix
    upload_signature = ("upload", uploaded_file.name, len(uploaded_bytes))
    if st.session_state.get("active_upload_signature") != upload_signature:
        _cleanup_session_temp_files()
        st.session_state.active_upload_signature = upload_signature

    video_path = save_uploaded_video_to_temp(uploaded_bytes, suffix, _session_temp_dir())
    return VideoSelection(
        name=uploaded_file.name,
        suffix=suffix,
        video_bytes=uploaded_bytes,
        video_path=video_path,
        signature=upload_signature,
        cleanup_path=True,
    )


@st.cache_data(show_spinner=False)
def _cached_video_summary(video_path: str) -> dict[str, float | int]:
    """Return cached video metadata for a local temporary file path."""
    return get_video_summary(Path(video_path))


def _metadata_table(metadata: dict[str, float | int]) -> pd.DataFrame:
    """Format video metadata for display."""
    return pd.DataFrame(
        {
            "Metric": ["FPS", "Frame count", "Duration seconds", "Width", "Height"],
            "Value": [
                round(float(metadata["fps"]), 2),
                metadata["frame_count"],
                round(float(metadata["duration_seconds"]), 2),
                metadata["width"],
                metadata["height"],
            ],
        }
    )


def _render_summary_table(table: pd.DataFrame) -> None:
    """Render a compact static two-column table without dataframe scrollbars."""
    rows = "\n".join(
        "<tr>"
        f"<td>{escape(str(row.Metric))}</td>"
        f"<td>{escape(str(row.Value))}</td>"
        "</tr>"
        for row in table.itertuples(index=False)
    )
    st.markdown(
        f"""
        <div style="
            border: 1px solid #e6e8ef;
            border-radius: 6px;
            display: inline-block;
            margin: 0.25rem 0 1rem 0;
            overflow: hidden;
        ">
        <table class="summary-table" style="
            border-collapse: collapse;
            font-size: 0.875rem;
            line-height: 1.35;
            min-width: 250px;
        ">
            <thead>
                <tr style="background: #f7f8fb;">
                    <th style="border-bottom: 1px solid #e6e8ef; padding: 0.5rem 0.75rem; text-align: left;">Metric</th>
                    <th style="border-bottom: 1px solid #e6e8ef; padding: 0.5rem 0.75rem; text-align: left;">Value</th>
                </tr>
            </thead>
            <tbody>{rows}</tbody>
        </table>
        </div>
        <style>
            table.summary-table td {{
                border-top: 1px solid #eef0f4;
                padding: 0.45rem 0.75rem;
                white-space: nowrap;
            }}
            table.summary-table td:first-child {{
                min-width: 135px;
            }}
            table.summary-table td:last-child {{
                min-width: 70px;
            }}
        </style>
        """,
        unsafe_allow_html=True,
    )


def _render_best_results() -> None:
    """Render short capture guidance for reviewers and users."""
    with st.expander("How to get best results"):
        for tip in BEST_RESULTS_TIPS:
            st.markdown(f"- {tip}")


def _target_min_matches(frame_count_hint: int | None) -> int:
    """Return the default alignment target: half the frames, capped at 60."""
    estimated_frames = frame_count_hint or 20
    return max(3, min(60, round(estimated_frames * 0.5)))


def _settings_from_sidebar(
    *,
    video_duration: float,
    frame_count_hint: int | None = None,
) -> tuple[PipelineSettings, bool]:
    """Collect Streamlit sidebar controls into pipeline settings."""
    default_min_matches = _target_min_matches(frame_count_hint)

    with st.sidebar:
        st.header("Processing")
        max_frames = st.slider(
            "Maximum frames",
            min_value=5,
            max_value=300,
            value=300,
            step=5,
        )
        frame_stride = st.number_input(
            "Frame stride",
            min_value=1,
            max_value=60,
            value=1,
            step=1,
        )
        start_time_s = st.number_input(
            "Start time seconds",
            min_value=0.0,
            value=0.0,
            step=0.5,
        )
        duration_s = st.number_input(
            "Duration seconds to process",
            min_value=0.1,
            value=video_duration if video_duration > 0 else 3.0,
            step=0.5,
        )
        reference_strategy = cast(
            ReferenceStrategy,
            st.selectbox(
                "Reference strategy",
                options=["median", "sharpest", "middle", "first"],
                index=0,
            ),
        )
        update_preview = st.button(
            "Update preview",
            type="secondary",
            use_container_width=True,
        )

        st.header("Alignment")
        enable_alignment = st.checkbox(
            "Enable alignment",
            value=True,
            help=(
                "For tripod star trails, disable alignment so the stars can trail. "
                "If using alignment for night scenes, guide it with static foreground."
            ),
        )
        orb_max_features = st.number_input(
            "Max ORB features",
            min_value=100,
            max_value=5000,
            value=1500,
            step=100,
        )
        orb_keep_matches = st.number_input(
            "Keep top matches",
            min_value=10,
            max_value=1000,
            value=200,
            step=10,
        )
        if (
            st.session_state.get("min_matches_target") != default_min_matches
            or st.session_state.get("min_matches", default_min_matches) > 60
        ):
            st.session_state.min_matches = default_min_matches
            st.session_state.min_matches_target = default_min_matches
        min_matches = st.number_input(
            "Minimum matches",
            min_value=3,
            max_value=60,
            key="min_matches",
            step=1,
        )
        min_inlier_ratio = st.slider(
            "Minimum inlier ratio (0.00 = Auto)",
            min_value=0.0,
            max_value=1.0,
            value=0.0,
            step=0.01,
            help=(
                "Set to 0.00 for auto mode. Auto starts at 1.00 and steps down "
                "until the minimum-match target is met. Any other value is a "
                "fixed cutoff."
            ),
        )
        ransac_reproj_threshold = st.number_input(
            "RANSAC reprojection threshold",
            min_value=0.5,
            max_value=20.0,
            value=3.0,
            step=0.5,
        )

        st.header("Stacking")
        stacking_label = st.selectbox(
            "Stacking mode",
            options=list(STACKING_MODE_LABELS),
            index=0,
        )
        stack_mode = STACKING_MODE_LABELS[stacking_label]
        st.caption(STACKING_MODE_GUIDANCE[stack_mode])
        sigma = st.number_input(
            "Sigma clipping",
            min_value=0.5,
            max_value=10.0,
            value=2.5,
            step=0.1,
        )
        additive_gain = 1.0
        if stack_mode == "additive":
            additive_gain = st.number_input(
                "Additive gain",
                min_value=0.0,
                max_value=10.0,
                value=1.0,
                step=0.1,
                help="Scales the summed frame values before clipping to 0..255.",
            )
        crop_borders = st.checkbox("Crop borders", value=True)
        valid_border_threshold = st.slider(
            "Valid border threshold",
            min_value=0.0,
            max_value=1.0,
            value=0.98,
            step=0.01,
        )

    settings = PipelineSettings(
        start_time_s=float(start_time_s),
        duration_s=float(duration_s),
        max_frames=int(max_frames),
        frame_stride=int(frame_stride),
        resize_width=None,
        reference_strategy=reference_strategy,
        orb_max_features=int(orb_max_features),
        orb_keep_matches=int(orb_keep_matches),
        min_matches=int(min_matches),
        min_inlier_ratio=float(min_inlier_ratio),
        ransac_reproj_threshold=float(ransac_reproj_threshold),
        enable_alignment=bool(enable_alignment),
        stack_mode=stack_mode,
        sigma=float(sigma),
        additive_gain=float(additive_gain),
        crop_borders=bool(crop_borders),
        valid_border_threshold=float(valid_border_threshold),
    )
    return settings, update_preview


def _preview_settings(settings: PipelineSettings, video_width: int) -> PipelineSettings:
    """Use the same processing window at a smaller width for mask preview."""
    preview_width = min(PREVIEW_RESIZE_WIDTH, video_width) if video_width > 0 else PREVIEW_RESIZE_WIDTH
    return replace(settings, resize_width=preview_width)


def _preview_signature(
    upload_signature: tuple[str, int],
    settings: PipelineSettings,
    video_width: int,
) -> tuple[object, ...]:
    """Return only the values that affect preview extraction/reference selection."""
    preview_width = min(PREVIEW_RESIZE_WIDTH, video_width) if video_width > 0 else PREVIEW_RESIZE_WIDTH
    return (
        upload_signature,
        settings.start_time_s,
        settings.duration_s,
        settings.max_frames,
        settings.frame_stride,
        settings.reference_strategy,
        preview_width,
    )


def _output_size_from_metadata(
    metadata: dict[str, float | int],
    resize_width: int | None,
) -> tuple[int, int]:
    """Return the expected final frame size as height, width."""
    source_width = int(metadata["width"])
    source_height = int(metadata["height"])
    if resize_width is None or resize_width <= 0 or resize_width >= source_width:
        return source_height, source_width

    output_height = max(1, round(source_height * resize_width / source_width))
    return output_height, int(resize_width)


def _extract_guidance_mask(
    canvas_result,
    background_rgb_display: np.ndarray,
    preview_size: tuple[int, int],
    output_size: tuple[int, int],
) -> tuple[np.ndarray | None, np.ndarray | None, float]:
    """Extract painted alpha and convert it to an ORB allowed-region mask."""
    paint_alpha = extract_paint_mask_from_canvas(
        canvas_result,
        background_rgb_display,
        preview_size,
    )
    coverage = float(np.mean(paint_alpha > 0.05))
    if coverage <= 0.0005:
        return None, None, 0.0

    if paint_alpha.shape != output_size:
        output_height, output_width = output_size
        paint_alpha = cv2.resize(
            paint_alpha,
            (output_width, output_height),
            interpolation=cv2.INTER_LINEAR,
        )

    allowed_mask = make_alignment_allowed_mask(paint_alpha)
    return paint_alpha, allowed_mask, float(np.mean(paint_alpha > 0.05))


def _crop_image_for_display(
    image_bgr: np.ndarray,
    crop_rect: tuple[int, int, int, int] | None,
) -> np.ndarray:
    """Crop an image by the pipeline crop rect when present."""
    if crop_rect is None:
        return image_bgr

    x_min, y_min, x_max, y_max = crop_rect
    return image_bgr[y_min:y_max, x_min:x_max]


def _split_comparison_image(
    reference_rgb: np.ndarray,
    final_rgb: np.ndarray,
) -> np.ndarray:
    """Build a left/right wipe comparison image."""
    if reference_rgb.shape != final_rgb.shape:
        raise ValueError("reference_rgb and final_rgb must have matching shapes")

    height, width = final_rgb.shape[:2]
    split_x = width // 2
    comparison = final_rgb.copy()
    comparison[:, :split_x] = reference_rgb[:, :split_x]

    line_x = int(np.clip(split_x, 1, max(1, width - 1)))
    cv2.line(comparison, (line_x, 0), (line_x, height), (255, 255, 255), 1)
    return comparison


def _render_output_viewer(
    final_rgb: np.ndarray,
    reference_rgb: np.ndarray | None,
    selected_count: int,
    mode_label: str,
) -> None:
    """Render final output with optional reference comparison modes."""
    viewer_options = ["Final output"]
    if reference_rgb is not None and reference_rgb.shape == final_rgb.shape:
        viewer_options.extend(["Reference vs final", "Split comparison"])

    viewer_mode = st.radio("Output view", viewer_options, horizontal=True)
    if viewer_mode == "Reference vs final" and reference_rgb is not None:
        reference_column, final_column = st.columns(2)
        reference_column.image(reference_rgb, caption="Reference frame")
        final_column.image(final_rgb, caption=f"{mode_label} ({selected_count} frames)")
    elif viewer_mode == "Split comparison" and reference_rgb is not None:
        comparison_rgb = _split_comparison_image(
            reference_rgb,
            final_rgb,
        )
        st.image(
            comparison_rgb,
            caption=f"Reference left, final right ({selected_count} frames)",
        )
    else:
        st.image(final_rgb, caption=f"{mode_label} ({selected_count} frames)")


def _render_preview_and_mask(
    preview: PreviewResult,
    *,
    can_process: bool,
) -> tuple[object | None, np.ndarray | None, bool]:
    """Render reference preview, sharpness plot, and mask canvas."""
    st.subheader("Reference and Alignment Guide")
    st.metric("Selected reference index", preview.reference_index)
    st.pyplot(
        sharpness_figure(preview.sharpness_scores, preview.reference_index),
        use_container_width=False,
    )

    if st_canvas is None:
        reference_rgb = cv2.cvtColor(preview.reference_frame_bgr, cv2.COLOR_BGR2RGB)
        st.image(reference_rgb, caption="Reference frame")
        st.error(
            "Install streamlit-drawable-canvas, then restart Streamlit to paint an alignment guide."
        )
        process_clicked = st.button(
            "Process image",
            type="primary",
            disabled=not can_process,
        )
        return None, None, process_clicked

    if "canvas_nonce" not in st.session_state:
        st.session_state.canvas_nonce = 0

    background_rgb_display, canvas_width, canvas_height = _canvas_background(
        preview.reference_frame_bgr,
        max_width=PREVIEW_RESIZE_WIDTH,
    )
    canvas_column, controls_column = st.columns([4, 1], gap="medium")
    with controls_column:
        brush_size = st.slider("Brush size", min_value=4, max_value=128, value=64, step=4)
        if st.button("Reset mask"):
            st.session_state.canvas_nonce += 1
            st.session_state.pop("guided_result", None)
        process_clicked = st.button(
            "Process image",
            type="primary",
            disabled=not can_process,
        )

    with canvas_column:
        canvas_result = st_canvas(
            fill_color="rgba(255, 255, 255, 0)",
            stroke_width=brush_size,
            stroke_color="#FFFFFF",
            background_image=Image.fromarray(background_rgb_display),
            update_streamlit=True,
            height=canvas_height,
            width=canvas_width,
            drawing_mode="freedraw",
            display_toolbar=False,
            key=f"alignment_guide_canvas_{st.session_state.canvas_nonce}",
        )
    return canvas_result, background_rgb_display, process_clicked


def _render_pipeline_result(result: PipelineResult, settings: PipelineSettings) -> None:
    """Render guided pipeline output and diagnostics."""
    st.subheader("Extraction")
    _render_summary_table(
        pd.DataFrame({"Metric": ["Frames processed"], "Value": [result.frames_processed]})
    )

    st.subheader("Alignment")
    metric_columns = st.columns(4)
    metric_columns[0].metric("Accepted frames", result.accepted_count)
    metric_columns[1].metric("Rejected frames", result.rejected_count)
    metric_columns[2].metric(
        "Applied minimum inlier ratio",
        f"{result.applied_min_inlier_ratio:.2f}",
    )
    metric_columns[3].metric("Guided mask coverage", f"{result.mask_coverage:.1%}")
    st.dataframe(
        pd.DataFrame(result.alignment_diagnostics),
        hide_index=True,
    )
    if result.alignment_results is not None:
        diagnostic_columns = st.columns(2)
        diagnostic_columns[0].pyplot(
            accepted_rejected_figure(result.alignment_results),
            use_container_width=False,
        )
        diagnostic_columns[1].pyplot(
            inlier_ratio_figure(result.alignment_results),
            use_container_width=False,
        )

    for warning in result.warnings:
        st.warning(warning)

    selected_count = result.accepted_count
    final_bgr = (
        result.cropped_output_image_bgr
        if result.cropped_output_image_bgr is not None
        else result.output_image_bgr
    )
    if result.alignment_results is not None and result.accepted_count > 0:
        stackable_count = len(stackable_alignment_order(result.alignment_results))
        initial_count = min(result.accepted_count, stackable_count)
        selected_count = st.slider(
            "# averaged frames",
            min_value=1,
            max_value=stackable_count,
            value=initial_count,
            step=1,
        )
        subset = stack_alignment_subset(
            result.alignment_results,
            selected_count,
            stack_mode=settings.stack_mode,
            sigma=settings.sigma,
            additive_gain=settings.additive_gain,
            crop_borders=settings.crop_borders,
            valid_border_threshold=settings.valid_border_threshold,
        )
        final_bgr = (
            subset.cropped_output_image_bgr
            if subset.cropped_output_image_bgr is not None
            else subset.output_image_bgr
        )
        display_crop_rect = subset.crop_rect
    else:
        display_crop_rect = result.crop_rect

    final_rgb = cv2.cvtColor(final_bgr, cv2.COLOR_BGR2RGB)
    reference_rgb = None
    if result.reference_frame_bgr is not None:
        reference_bgr = _crop_image_for_display(
            result.reference_frame_bgr,
            display_crop_rect,
        )
        if reference_bgr.shape == final_bgr.shape:
            reference_rgb = cv2.cvtColor(reference_bgr, cv2.COLOR_BGR2RGB)

    _save_output_images(final_bgr)
    png_bytes = _encode_image(final_bgr, ".png")
    jpg_bytes = _encode_image(final_bgr, ".jpg")

    output_label = OUTPUT_SECTION_LABELS[settings.stack_mode]
    st.subheader(output_label)
    _render_output_viewer(
        final_rgb,
        reference_rgb,
        selected_count,
        output_label,
    )
    download_columns = st.columns(2)
    download_columns[0].download_button(
        "Download PNG",
        data=png_bytes,
        file_name="long_exposure.png",
        mime="image/png",
    )
    download_columns[1].download_button(
        "Download JPEG",
        data=jpg_bytes,
        file_name="long_exposure.jpg",
        mime="image/jpeg",
    )


def _canvas_background(reference_bgr: np.ndarray, max_width: int = 700) -> tuple[np.ndarray, int, int]:
    """Build a display-sized RGB canvas background."""
    reference_rgb = cv2.cvtColor(reference_bgr, cv2.COLOR_BGR2RGB)
    height, width = reference_rgb.shape[:2]
    display_width = min(max_width, width)
    display_height = max(1, round(height * display_width / width))
    background_rgb_display = cv2.resize(
        reference_rgb,
        (display_width, display_height),
        interpolation=cv2.INTER_AREA,
    )
    return background_rgb_display, display_width, display_height


def main() -> None:
    """Render the Streamlit app."""
    st.set_page_config(page_title=APP_TITLE, layout="wide")
    _inject_ui_styles()
    st.title(APP_TITLE)
    st.caption("A local portfolio lab for honest frame averaging from video.")

    selected_video = None

    try:
        selected_video = _render_video_input()
    except ValueError as error:
        st.error(str(error))
        return

    if selected_video is None:
        st.info("Upload a short local video or choose a demo sample to begin.")
        return

    if st.session_state.get("video_signature") != selected_video.signature:
        st.session_state.video_signature = selected_video.signature
        st.session_state.pop("preview_result", None)
        st.session_state.pop("preview_signature", None)
        st.session_state.pop("guided_result", None)
        st.session_state.pop("guided_settings", None)
        st.session_state.pop("canvas_nonce", None)

    try:
        summary = _cached_video_summary(str(selected_video.video_path))
        video_width = int(summary["width"])
        video_duration = float(summary["duration_seconds"])
        _render_video(
            _video_bytes_for_display(selected_video),
            suffix=selected_video.suffix,
            video_width=video_width,
        )

        preview_result = st.session_state.get("preview_result")
        frame_count_hint = (
            preview_result.frames_processed
            if isinstance(preview_result, PreviewResult)
            else None
        )
        settings, update_preview = _settings_from_sidebar(
            video_duration=video_duration,
            frame_count_hint=frame_count_hint,
        )
        preview_settings = _preview_settings(settings, video_width)
        preview_signature = _preview_signature(
            selected_video.signature,
            settings,
            video_width,
        )
        preview_is_stale = st.session_state.get("preview_signature") != preview_signature

        st.subheader("Video Metadata")
        _render_summary_table(_metadata_table(summary))
        if max(video_width, int(summary["height"])) > 2048:
            st.warning(
                "For the hosted Streamlit demo, 2K or smaller video is recommended. "
                "4K clips may run out of memory during full-resolution processing."
            )
        _render_best_results()

        if update_preview or preview_result is None:
            with st.status("Preparing mask preview", expanded=True) as status:
                st.write("Extracting preview frames and selecting the reference.")
                preview_result = run_preview(selected_video.video_path, preview_settings)
                st.session_state.preview_result = preview_result
                st.session_state.preview_signature = preview_signature
                st.session_state.canvas_nonce = st.session_state.get("canvas_nonce", 0) + 1
                st.session_state.pop("guided_result", None)
                status.update(label="Preview ready", state="complete")
            preview_is_stale = False
        elif preview_is_stale:
            st.warning("Preview settings changed. Update the preview before processing the image.")

        if preview_result is None:
            st.info("Update the preview to choose the reference frame and paint an alignment guide.")
            return

        preview_result = cast(PreviewResult, preview_result)
        if preview_result.frames_processed > PREVIEW_FRAME_REFRESH_THRESHOLD and preview_is_stale:
            st.warning("This clip uses more than 120 preview frames, so the preview needs to be refreshed before processing.")

        can_run_pipeline = not (
            preview_is_stale and preview_result.frames_processed > PREVIEW_FRAME_REFRESH_THRESHOLD
        )
        canvas_result, background_rgb_display, process_clicked = _render_preview_and_mask(
            preview_result,
            can_process=can_run_pipeline,
        )

        if process_clicked:
            alignment_allowed_mask = None
            mask_coverage = 0.0
            if canvas_result is not None and background_rgb_display is not None:
                _paint_alpha, alignment_allowed_mask, mask_coverage = _extract_guidance_mask(
                    canvas_result,
                    background_rgb_display,
                    preview_result.reference_frame_bgr.shape[:2],
                    _output_size_from_metadata(summary, settings.resize_width),
                )

            with st.status("Processing video", expanded=True) as status:
                st.write("Extracting full-resolution frames.")
                if alignment_allowed_mask is not None:
                    st.write(f"Using painted alignment guide ({mask_coverage:.1%} masked).")
                st.write("Aligning accepted frames and building the full-frame average.")
                result = run_pipeline(
                    selected_video.video_path,
                    settings,
                    alignment_allowed_mask,
                )
                st.session_state.guided_result = result
                st.session_state.guided_settings = settings
                status.update(label="Processing complete", state="complete")

        result = st.session_state.get("guided_result")
        result_settings = st.session_state.get("guided_settings", settings)
        if result is None:
            st.info("Process the image when the reference and mask are ready.")
            return

        _render_pipeline_result(cast(PipelineResult, result), cast(PipelineSettings, result_settings))
    except ValueError as error:
        st.error(str(error))
    finally:
        if selected_video is not None and selected_video.cleanup_path:
            selected_video.video_path.unlink(missing_ok=True)


if __name__ == "__main__":
    main()
